"""relation to_name unique index

Revision ID: b3c3938bacdb
Revises: 3dae7c7b1564
Create Date: 2025-02-22 14:59:30.668466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3c3938bacdb'
down_revision: Union[str, None] = '3dae7c7b1564'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_relation_from_id_to_id', 'relation', ['from_id', 'to_id', 'relation_type'])
    op.create_unique_constraint('uix_relation_from_id_to_name', 'relation', ['from_id', 'to_name', 'relation_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_relation_from_id_to_name', 'relation', type_='unique')
    op.drop_constraint('uix_relation_from_id_to_id', 'relation', type_='unique')
    op.create_unique_constraint('uix_relation', 'relation', ['from_id', 'to_id', 'relation_type'])
    # ### end Alembic commands ###
